version: '3'
services:
  bfextractor:
    build: .
    environment:
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      STACKPREFIX: minerva-test
      STAGE: dev
      DEBUG: "True"
    volumes:
      - /data:/tmp/aws
    command:
      # Import UUID and also the directory name within /data
      - importUuid
      # Location of entrypoint within importUuid directory
      - path/to/entrypoint/example.dv
      # Identify for the Bio-Formats Reader
      - loci.formats.in.DeltavisionReader
      # Reader Software Name
      - Bio-Formats
      # Reader Software Version
      - UNKNOWN
      # Bucket in which to write tiles
      - jmuhlich-bfextractor-test
      # BFU UUID
      - bfuUuid
